
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: nodejs-app-latest
  namespace: nodejs-acm
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  sourceNamespaces:
    - nodejs-acm
  type: Git
  pathname: https://github.com/canhissare/rhacm-pipelines.git